apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica
spec:
  serviceName: mysql
  replicas: 2   # ← start with 2, scale up later with kubectl scale sts/mysql-replica --replicas=3
  selector:
    matchLabels:
      app: mysql
      role: replica
  template:
    metadata:
      labels:
        app: mysql
        role: replica
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mysql
          image: bitnami/mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_REPLICATION_MODE
              value: "slave"
            - name: MYSQL_MASTER_HOST
              value: "mysql-primary-0.mysql-primary-0-service"   # ← DNS name of primary pod
            - name: MYSQL_MASTER_PORT_NUMBER
              value: "3306"
            - name: MYSQL_REPLICATION_USER
              value: "repl_user"
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_REPLICATION_PASSWORD
            # No MYSQL_DATABASE/USER/PASSWORD here → replicas clone from primary
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "--silent"]
            initialDelaySeconds: 45   # replicas take longer to catch up
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "--silent"]
            initialDelaySeconds: 90
            periodSeconds: 10
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
