apiVersion: v1
kind: Service
metadata:
  name: mysql-primary-service"   # ← DNS name of primary podysql
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: mysql
  selector:
    app: mysql
    role: primary
